#!/usr/bin/env bash
# scripts/ci-generate-cli-surface.sh
#
# Generate ZODER_CLI_SURFACE.txt from the live Clap command tree.
# CI fails if this output drifts from the committed snapshot.
#
# Usage (in CI):
#   scripts/ci-generate-cli-surface.sh     # generate and diff
#   scripts/ci-generate-cli-surface.sh --update  # overwrite the committed file
set -euo pipefail

echo "Building zoder..."
if ! cargo build --quiet 2>&1; then
  echo "ERROR: Build failed — cannot generate CLI surface." >&2
  exit 1
fi

ZODER="./target/debug/zoder"

# All known subcommand names (must stay in sync with Cmd enum in zoder-cli).
SUBCOMMANDS=(
  exec tui models update route consult spend report health finops
  providers config refresh pricing reconcile sessions
  review adversarial-review rescue status result cancel jobs
  loop transfer session recipe mcp mcp-server configure completions gate
)

{
  echo "# zoder CLI Surface (Command Tree)"
  echo "#"
  echo "# Generated by \`scripts/ci-generate-cli-surface.sh\` from the live"
  echo "# Clap command tree (the \`--help\` output of every subcommand)."
  echo "# This file is a committed snapshot of that output."
  echo "#"
  echo "# CI fails if \`ZODER_CLI_SURFACE.txt\` drifts from the actual CLI surface."
  echo "# To update: \`cargo build --quiet && scripts/ci-generate-cli-surface.sh --update\`"
  echo "#"
  echo "# Format: sectioned \`--help\` output for the main command and each subcommand."
  echo "# The sections are sorted by subcommand name for deterministic output."
  echo "#"
  echo "zoder: Free-first, cost-aware, codex-compatible coding CLI"
  echo ""

  # Main help
  "$ZODER" --help 2>&1
  echo ""

  # Subcommand help (sorted for deterministic output)
  printf "%s\n" "${SUBCOMMANDS[@]}" | sort | while read -r sub; do
    echo "zoder $sub:"
    echo ""
    "$ZODER" "$sub" --help 2>&1
    echo ""
  done

  echo "# End of CLI surface"
} > /tmp/zoder-cli-surface-$$

# Decide whether to diff in-place or overwrite the committed file.
UPDATE_MODE=false
if [ "${1:-}" = "--update" ]; then
  UPDATE_MODE=true
fi

COMMITTED="ZODER_CLI_SURFACE.txt"

if "$UPDATE_MODE"; then
  cp /tmp/zoder-cli-surface-$$ "$COMMITTED"
  echo "Updated $COMMITTED with fresh CLI surface."
  rm -f /tmp/zoder-cli-surface-$$
  exit 0
fi

if ! diff -q "$COMMITTED" /tmp/zoder-cli-surface-$$ >/dev/null 2>&1; then
  echo "ERROR: CLI surface drift detected!" >&2
  echo "The live --help output no longer matches the committed snapshot." >&2
  echo "" >&2
  diff -u "$COMMITTED" /tmp/zoder-cli-surface-$$ || true
  echo "" >&2
  echo "To fix: run \`scripts/ci-generate-cli-surface.sh --update\` and commit" >&2
  echo "the updated ZODER_CLI_SURFACE.txt, or verify that the drift is intentional." >&2
  rm -f /tmp/zoder-cli-surface-$$
  exit 1
fi

echo "CLI surface is in sync (no drift)."
rm -f /tmp/zoder-cli-surface-$$
exit 0